# Builds the images as a correctness check.
name: Build

on:
  pull_request:
    paths:
      - db/*
      - web/*
      - docker-compose.yml

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: docker/setup-buildx-action@v1

      - name: Build DB
        uses: docker/build-push-action@v2
        with:
          context: ./db
          push: false

      - name: Build Web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: false
